---
# tasks file for nextcloud
 - name: Include update OS
   include_tasks: update.yml

 - name: Include installing prerequisites
   include_tasks: prerequisites.yml

 - name: Include disabling SELinux until reboot
   include_tasks: disable-selinux.yml

 - name: Include install and configure Apache HTTP server
   include_tasks: apache.yml 
